### ISSUE TITLE
HTML snippets in the markdown file

### ISSUE THREAD

**Issue by sebschlo** [yaru22/angular-md#3]
Hi, thanks for writing this, it's just what I needed and it works great! I'm just wondering if it's possible for html snippets in the markdown to be included in the page. For example, I have <iframe> tags inside the markdown text that I'm using linking to videos and such and it would be great for them to be rendered in the page as well. Currently, they are just skipped.

**Comment by jasonrichardsmith** [comment]
I am having a similar issue.
These are using the same exact markdown files:

http://mongular.org/docs/templates

https://github.com/mongular/mongular/wiki/Templates

I am not sure if this is a marked issue or not.

**Comment by yaru22** [comment]
@jasonrichardsmith Could you try the markdown you have at http://brianpark.ca/projects/angular_md/demo/ (in Dynamic Markdown Renderer) and see if it works? When I tried it there, it worked fine.
